-- 현재 사용자 스키마에 포함된 테이블 목록 조회
SELECT TABLE_NAME FROM USER_TABLES;

-- 테이블 정보 조회
DESC BOOK;

-- 단일 테이블에서 조회하면 관계있는 데이터를 볼 수 없습니다.
SELECT * 
FROM ORDERS;

-- 1-1. 두 개의 테이블에 있는 데이터를 결합해서 조회
SELECT *
FROM CUSTOMER, ORDERS;

-- 1-2. 두 개의 테이블에 있는 데이터를 결합해서 조회
SELECT *
FROM CUSTOMER
CROSS JOIN ORDERS;

-- 2-1. 고객과 고객의 주문 데이터 조회
SELECT CUSTOMER.CUSTID, NAME, PHONE, ORDERID, BOOKID, SALEPRICE, ORDERDATE
FROM CUSTOMER, ORDERS
WHERE CUSTOMER.CUSTID = ORDERS.CUSTID -- 관계 있는 컬럼으로 조건 구성
ORDER BY CUSTOMER.CUSTID;

-- 2-2. 고객과 고객의 주문 데이터 조회
SELECT C.CUSTID, C.NAME, C.PHONE, O.ORDERID, O.BOOKID, O.SALEPRICE, O.ORDERDATE
FROM CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID -- 관계 있는 컬럼으로 조건 구성
ORDER BY C.CUSTID;

-- 2-3. 고객과 고객의 주문 데이터 조회
SELECT C.CUSTID, C.NAME, C.PHONE, O.ORDERID, O.BOOKID, O.SALEPRICE, O.ORDERDATE
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID -- JOIN 조건은 ON 절에 작성
ORDER BY C.CUSTID;

-- 3-1. 고객의 이름과 고객이 주문한 도서 이름 및 판매가격 조회
SELECT C.NAME, O.BOOKID, O.SALEPRICE
FROM CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID
ORDER BY C.CUSTID;

-- 3-2. 고객의 이름과 고객이 주문한 도서 이름 및 판매가격 조회
SELECT C.NAME, O.BOOKID, O.SALEPRICE
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
ORDER BY C.CUSTID;

-- 4-1. 고객의 이름과 총 주문액 조회
SELECT C.NAME, SUM(O.SALEPRICE)
FROM CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID
GROUP BY C.NAME
ORDER BY C.NAME;

-- 4-2. 고객의 이름과 총 주문액 조회
SELECT C.NAME, SUM(O.SALEPRICE)
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
GROUP BY C.NAME
ORDER BY C.NAME;

-- 5-1. 고객의 이름과 고객이 주문한 도서의 이름, 도서 가격, 준문 금액 조회.
SELECT C.NAME, B.BOOKNAME, B.PRICE, O.SALEPRICE
FROM CUSTOMER C, BOOK B, ORDERS O
WHERE C.CUSTID = O.CUSTID AND B.BOOKID = O.BOOKID
ORDER BY C.NAME;

-- 5-2. 고객의 이름과 고객이 주문한 도서의 이름, 도서 가격, 준문 금액 조회.
SELECT C.NAME, B.BOOKNAME, B.PRICE, O.SALEPRICE
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B 
ON B.BOOKID = O.BOOKID
ORDER BY C.NAME;

-- 5-3. 가격이 20000인 도서를 구매한 고객이름, 도서이름, 도서가격, 준문금액 조회.
SELECT C.NAME, B.BOOKNAME, B.PRICE, O.SALEPRICE
FROM CUSTOMER C, BOOK B, ORDERS O
WHERE B.PRICE = 20000
      AND C.CUSTID = O.CUSTID 
      AND B.BOOKID = O.BOOKID
ORDER BY C.NAME;

-- 5-4. 가격이 20000인 도서를 구매한 고객이름, 도서이름, 도서가격, 준문금액 조회.
SELECT C.NAME, B.BOOKNAME, B.PRICE, O.SALEPRICE
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B 
ON B.BOOKID = O.BOOKID
WHERE B.PRICE = 20000
ORDER BY C.NAME;

-- 6-1. 고객별 주문 총액 조회 (고객이름, 주문총액)
--      NVL(표현식, null 대체값) : 표현식이 null이면 null 대체 값 사용
SELECT C.NAME, NVL(SUM(O.SALEPRICE), 0) 주문총액
FROM CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID(+)
GROUP BY C.NAME
ORDER BY 주문총액 DESC;

-- 6-2. 고객별 주문 총액 조회 (고객이름, 주문총액)
--      NVL(표현식, null 대체값) : 표현식이 null이면 null 대체 값 사용
SELECT C.NAME, NVL(SUM(O.SALEPRICE), 0) 주문총액
FROM CUSTOMER C
LEFT OUTER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
GROUP BY C.NAME
ORDER BY 주문총액 DESC;







