-- 0. 테이블 정보 보기
DESC EMPLOYEES; -- DESCRIBE EMPLOYEES

-- 1. EMPLOYEES 테이블에서 
--    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID 조회

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES;

SELECT 
    EMPLOYEE_ID, 
    FIRST_NAME || ' ' || LAST_NAME, -- || : ORACLE의 문자열 결합 연산자
    SALARY, 
    DEPARTMENT_ID
FROM EMPLOYEES;

-- 2. 직원수 조회
SELECT COUNT(EMPLOYEE_ID) 직원수
FROM EMPLOYEES;

-- 3. 부서별 직원수 조회
SELECT DEPARTMENT_ID 부서코드, COUNT(EMPLOYEE_ID) 직원수
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY COUNT(EMPLOYEE_ID) DESC;

-- 4. 부서코드가 50, 80인 부서이름 조회
SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID IN (50, 80);

-- 5. 부서별 직원 조회 (부서명으로 집계)
SELECT D.DEPARTMENT_NAME, COUNT(*)
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
ORDER BY COUNT(*) DESC;

-- 6. 부서에 소속되지 않은 직원 조회
SELECT *
FROM EMPLOYEES
-- WHERE DEPARTMENT_ID = NULL; -- NULL을 비교 연산자로 비교할 수 없습니다.
WHERE DEPARTMENT_ID IS NULL; -- IS NULL : NULL 비교

-- 7. 근속기간순으로 직원 조회
SELECT *
FROM EMPLOYEES
ORDER BY HIRE_DATE ASC;

-- 8. 급여순으로 직원 조회
SELECT *
FROM EMPLOYEES
ORDER BY SALARY DESC;

-- 9. 급여가 많은 상위 5명을 조회하세요
SELECT ROWNUM, EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES E
ORDER BY E.SALARY DESC;

SELECT B.*
FROM
(
    SELECT ROWNUM 순위, A.*
    FROM (
        SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
        FROM EMPLOYEES E
        ORDER BY E.SALARY DESC
    ) A
) B
WHERE B.순위 <= 5;
-- WHERE B.순위 BETWEEN 10 AND 20;

-- 10. 급여 평균, 최저 급여, 최고 급여 조회
SELECT MAX(SALARY), MIN(SALARY), AVG(SALARY)
FROM EMPLOYEES;

-- 11. EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME, 
--     MANAGER_NAME (FIRST_NAME || ' ' || LAST_NAME) 조회
SELECT 
    E.EMPLOYEE_ID,
    E.FIRST_NAME || ' ' || E.LAST_NAME 직원이름,
    M.FIRST_NAME || ' ' || M.LAST_NAME 관리자이름
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID;









