-- 테이블 만들기 1
CREATE TABLE NEWBOOK 
(
    -- 컬럼이름 자료형
    BOOKID NUMBER,
    BOOKNAME VARCHAR2(100),
    PUBLISHER VARCHAR2(100),
    PRICE NUMBER
);

DROP TABLE NEWBOOK; -- 테이블 제거

-- 테이블 만들기 2
CREATE TABLE NEWBOOK 
(
    -- 컬럼이름 자료형 NULL허용
    BOOKID      NUMBER          NOT NULL,
    BOOKNAME    VARCHAR2(100)   NOT NULL,
    PUBLISHER   VARCHAR2(100)   NOT NULL,
    PRICE       NUMBER          NULL
);

DROP TABLE NEWBOOK;

-- 테이블 만들기 3
CREATE TABLE NEWBOOK 
(
    -- 컬럼이름 자료형 NULL허용 기본값
    BOOKID      NUMBER          NOT NULL,
    BOOKNAME    VARCHAR2(100)   NOT NULL,
    PUBLISHER   VARCHAR2(100)   NOT NULL,
    PRICE       NUMBER                      DEFAULT (0)
);
DROP TABLE NEWBOOK;

-- 테이블 만들기 4
CREATE TABLE NEWBOOK 
(
    -- 컬럼이름 자료형 NULL허용 기본값 기본키설정
    BOOKID      NUMBER          NOT NULL    PRIMARY KEY,
    BOOKNAME    VARCHAR2(100)   NOT NULL,
    PUBLISHER   VARCHAR2(100)   NOT NULL,
    PRICE       NUMBER                      DEFAULT (0)
);
DROP TABLE NEWBOOK;

-- 테이블 만들기 5
CREATE TABLE NEWBOOK 
(
    -- 컬럼이름 자료형 NULL허용 기본값 기본키설정
    BOOKID      NUMBER          NOT NULL,
    BOOKNAME    VARCHAR2(100)   NOT NULL,
    PUBLISHER   VARCHAR2(100)   NOT NULL,
    PRICE       NUMBER                      DEFAULT (0),
    PRIMARY KEY (BOOKID)
);
DROP TABLE NEWBOOK;

-- 테이블 만들기 6
CREATE TABLE NEWBOOK 
(
    -- 컬럼이름 자료형 NULL허용 기본값 CHECK제약
    BOOKID      NUMBER          NOT NULL,
    BOOKNAME    VARCHAR2(100)   NOT NULL,
    PUBLISHER   VARCHAR2(100)   NOT NULL,
    PRICE       NUMBER                      DEFAULT (0) CHECK(PRICE >= 0),
    PRIMARY KEY (BOOKID)
);
DROP TABLE NEWBOOK;

-- 7. 테이블 만들기
CREATE TABLE NEWCUSTOMER
(
    CUSTID NUMBER NOT NULL,
    NAME VARCHAR2 (40 CHAR) NOT NULL,
    ADDRESS VARCHAR2 (40 CHAR) NOT NULL,
    PHONE VARCHAR2 (30 BYTE) NOT NULL,
    PRIMARY KEY (CUSTID)
);

-- 8. 테이블 만들기
SELECT SYSDATE FROM DUAL; -- DUAL : 임시 테이블

CREATE TABLE NEWORDERS
(
    ORDERID NUMBER NOT NULL,
    CUSTID NUMBER NOT NULL,
    BOOKID NUMBER NOT NULL,
    SALEPRICE NUMBER DEFAULT 0,
    ORDERDATE DATE DEFAULT SYSDATE, -- 현재시간을 기본 값으로 지정
    PRIMARY KEY (ORDERID),
    FOREIGN KEY (CUSTID) REFERENCES NEWCUSTOMER(CUSTID),
    FOREIGN KEY (BOOKID) REFERENCES NEWBOOK(BOOKID)
);

-- 자동 증가 값을 생산하는 객체 만들기
CREATE SEQUENCE ORDER_SEQUENCE;

SELECT ORDER_SEQUENCE.NEXTVAL FROM DUAL; -- 다음 순서번호
SELECT ORDER_SEQUENCE.CURRVAL FROM DUAL; -- 마지막으로 뽑은 순서번호

-- 테이블 수정 구문 테스트를 위한 테이블 만들기
CREATE TABLE NEWBOOK2 
(
    BOOKID      NUMBER,
    BOOKNAME    VARCHAR2(100),
    PUBLISHER   VARCHAR2(100),
    PRICE       NUMBER
);

-- 테이블 수정 1
ALTER TABLE NEWBOOK2
ADD ISBN VARCHAR2(13) NOT NULL;

-- 테이블 수정 2
ALTER TABLE NEWBOOK2
MODIFY ISBN NUMBER;

-- 테이블 수정 3
ALTER TABLE NEWBOOK2
DROP COLUMN ISBN;

-- 테이블 수정 4
ALTER TABLE NEWBOOK2
MODIFY BOOKID NUMBER NOT NULL;

-- 테이블 수정 5
ALTER TABLE NEWBOOK2
-- ADD PRIMARY KEY (BOOKID);
ADD CONSTRAINT PK_BOOKID PRIMARY KEY (BOOKID);

-- 테이블 수정 6
ALTER TABLE NEWBOOK2
DROP PRIMARY KEY;

-- 테이블 수정을 위한 테이블 만들기
CREATE TABLE NEWBOOK_DETAIL
(
    DETAILID NUMBER NOT NULL PRIMARY KEY,
    BOOKID NUMBER NOT NULL -- NEWBOOK 테이블을 참조하는 컬럼 (FOREIGN KEY)
);

-- 테이블 수정 7
ALTER TABLE NEWBOOK_DETAIL
ADD CONSTRAINT FK_NEWBOOK_DETAIL 
    FOREIGN KEY (BOOKID) REFERENCES NEWBOOK (BOOKID);
    
-- 테이블 삭제 1
DROP TABLE NEWBOOK; -- 참조하는 테이블이 있어서 삭제 실패

-- 테이블 삭제 2
DROP TABLE NEWBOOK_DETAIL;










