-- 0. 테이블 정보 보기
DESC EMPLOYEES; -- DESCRIBE EMPLOYEES

-- 1. EMPLOYEES 테이블에서
--    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME, SALARY, DEPARTMENT_ID -- || ORACLE의 문자열 결합 연산자
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, CONCAT(CONCAT(FIRST_NAME, ' '), LAST_NAME), SALARY, DEPARTMENT_ID -- || ORACLE의 문자열 결합 연산자
FROM EMPLOYEES;

-- 2. 직원수 조회 
SELECT COUNT(EMPLOYEE_ID) 직원수
FROM EMPLOYEES;

-- 3. 부서별 직원수 조회
SELECT DEPARTMENT_ID 부서코드, COUNT(EMPLOYEE_ID) 직원수
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY 직원수 DESC;

-- 4. 부서코드가 50, 80인 부서이름 조회
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE DEPARTMENT_ID IN (50, 80);

-- 5. 부서별 직원수 조회 (부서명으로 집계)
SELECT D.DEPARTMENT_NAME, COUNT(*)
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
ORDER BY COUNT(*) DESC;

-- 6. 부서에 소속되지 않은 직원 조회
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

-- 7. 근속기간순으로 직원 조회
SELECT *
FROM EMPLOYEES
ORDER BY HIRE_DATE;

-- 8. 급여순으로 직원 조회
SELECT *
FROM EMPLOYEES
ORDER BY SALARY DESC;

-- 9. 급여가 많은 상위 5명을 조회
SELECT *
FROM (
      SELECT *
      FROM EMPLOYEES
      ORDER BY SALARY DESC
    )
WHERE ROWNUM <= 5;

-- 10. 급여 평균, 최저 급여, 최고 급여 조회
SELECT AVG(SALARY), MIN(SALARY), MAX(SALARY)
FROM EMPLOYEES;

