-- QUIZ3

-- 1-1. 박지성 고객이 구매한 도서의 출판사 수
SELECT COUNT(DISTINCT B.PUBLISHER) "출판사 수"
FROM BOOK B, ORDERS O, CUSTOMER C
WHERE C.NAME = '박지성' AND B.BOOKID = O.BOOKID AND C.CUSTID = O.CUSTID;

-- 1-2. 박지성 고객이 구매한 도서의 출판사 수
SELECT COUNT(DISTINCT B.PUBLISHER) "출판사 수"
FROM BOOK B
INNER JOIN ORDERS O
ON B.BOOKID = O.BOOKID
INNER JOIN CUSTOMER C
ON C.CUSTID = O.CUSTID
WHERE C.NAME = '박지성';

-- 2-1. 박지성이 구매한 도서의 이름, 가격, 정가와 판매가격의 차이
SELECT B.BOOKNAME, B.PRICE, (B.PRICE - O.SALEPRICE) DISCOUNT
FROM BOOK B, ORDERS O, CUSTOMER C
WHERE C.NAME = '박지성' AND B.BOOKID = O.BOOKID AND C.CUSTID = O.CUSTID;

-- 2-2. 박지성이 구매한 도서의 이름, 가격, 정가와 판매가격의 차이
SELECT B.BOOKNAME, B.PRICE, (B.PRICE - O.SALEPRICE) DISCOUNT
FROM BOOK B
INNER JOIN ORDERS O
ON B.BOOKID = O.BOOKID
INNER JOIN CUSTOMER C
ON C.CUSTID = O.CUSTID
WHERE C.NAME = '박지성';

-- 3-1. 박지성이 구매하지 않은 도서의 이름
SELECT DISTINCT B.BOOKNAME
FROM BOOK B, ORDERS O
WHERE B.BOOKID = O.BOOKID(+) 
    AND (O.CUSTID <> (SELECT C.CUSTID FROM CUSTOMER C WHERE C.NAME = '박지성') 
        OR O.CUSTID IS NULL); -- 아무도 주문하지 않은 도서 (NULL은 연산자(=)로 비교 X)
    
-- 3-2. 박지성이 구매하지 않은 도서의 이름
SELECT BOOKNAME
FROM BOOK
MINUS 
SELECT BOOKNAME
FROM BOOK B, ORDERS O, CUSTOMER C
WHERE B.BOOKID = O.BOOKID AND C.CUSTID = O.CUSTID AND C.NAME = '박지성';

-- 3-3. 박지성이 구매하지 않은 도서의 이름
SELECT BOOKNAME
FROM BOOK
WHERE BOOKNAME NOT IN ( SELECT BOOKNAME
                        FROM BOOK B, ORDERS O, CUSTOMER C
                        WHERE B.BOOKID = O.BOOKID AND C.CUSTID = O.CUSTID AND C.NAME = '박지성');

-- 4-1. 주문하지 않은 고객의 이름
SELECT NAME
FROM CUSTOMER
WHERE CUSTID NOT IN ( SELECT CUSTID FROM ORDERS);

-- 5-1. 주문 금액의 총액과 주문의 평균 금액
SELECT SUM(SALEPRICE), AVG(SALEPRICE)
FROM ORDERS;

-- 6-1. 고객의 이름과 고객별 구매액
SELECT C.NAME, SUM(O.SALEPRICE) 구매액
FROM CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID
GROUP BY C.NAME
ORDER BY 구매액 DESC;

-- 6-2. 고객의 이름과 고객별 구매액
SELECT C.NAME, NVL(SUM(O.SALEPRICE), 0) 구매액
FROM CUSTOMER C
LEFT OUTER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
GROUP BY C.NAME
ORDER BY 구매액 DESC;

-- 7-1. 고객의 이름과 고객이 구매한 도서 목록 (주문하지 않은 고객 포함)
SELECT C.NAME, NVL(B.BOOKNAME, '-')
FROM CUSTOMER C
LEFT OUTER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
LEFT OUTER JOIN BOOK B
ON O.BOOKID = B.BOOKID
ORDER BY C.NAME;

-- 8-1. 도서의 가격(Book 테이블)과 판매가격(Order 테이블)의 차이가 가장 많은 주문

SELECT MAX(B.PRICE - O.SALEPRICE)
FROM BOOK B
INNER JOIN ORDERS O
ON B.BOOKID = O.BOOKID;

SELECT O.ORDERID, B.BOOKNAME, (B.PRICE - O.SALEPRICE) 할인액
FROM BOOK B
INNER JOIN ORDERS O
ON B.BOOKID = O.BOOKID
WHERE B.PRICE - O.SALEPRICE = ( SELECT MAX(B.PRICE - O.SALEPRICE)
                                FROM BOOK B
                                INNER JOIN ORDERS O
                                ON B.BOOKID = O.BOOKID );

-- 9-1. 도서의 판매액 평균보다 자신의 구매액 평균이 더 높은 고객의 이름
SELECT C.NAME, AVG(O.SALEPRICE) 평균구매액
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
GROUP BY C.NAME
HAVING AVG(O.SALEPRICE) > (SELECT AVG(SALEPRICE) FROM ORDERS);
