-- 1. 테이블 만들기 1
CREATE TABLE MEMBER
(
    MEMBERID VARCHAR2(100) NOT NULL,
    PASSWD VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NULL,
    PHONE VARCHAR2(100) NULL,
    USERTYPE VARCHAR2(10) DEFAULT('USER') CHECK(USERTYPE IN ('USER', 'ADMIN')),
    REGDATE DATE DEFAULT(SYSDATE),
    ACTIVE CHAR(1) DEFAULT('1'),
    PRIMARY KEY(MEMBERID)
);

-- 2. 테이블 만들기 2
CREATE TABLE BOARD
(
    BOARDNO NUMBER NOT NULL,
    TITLE VARCHAR2(100 CHAR) NOT NULL,
    WRITER VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(500) NOT NULL,
    REGDATE DATE DEFAULT(SYSDATE),
    READCOUNT NUMBER DEFAULT(0) CHECK(READCOUNT >= 0),
    DELETED CHAR(1) DEFAULT('0'),
    PRIMARY KEY(BOARDNO)
);

-- 3. 테이블 수정
ALTER TABLE BOARD
ADD FOREIGN KEY(WRITER) REFERENCES MEMBER(MEMBERID);

-- 4. 시퀀스 만들기
CREATE SEQUENCE BOARD_SEQUENCE NOCACHE; -- NOCACHE : CACHE를 사용하지 않음

-- 5. MEMBER 테이블에 데이터 삽입
INSERT ALL
INTO MEMBER (MEMBERID, PASSWD, EMAIL, PHONE)
VALUES ('iamuserone', '9922', 'iamuserone@example.com', '010-3625-4758')
INTO MEMBER (MEMBERID, PASSWD, EMAIL, PHONE, USERTYPE)
VALUES ('iamusertwo', '9922', 'iamusertwo@example.com', '010-4587-1246', 'ADMIN')
INTO MEMBER (MEMBERID, PASSWD, EMAIL, PHONE, REGDATE, ACTIVE)
VALUES ('iamuserthree', '9922', 'iamuserthree@example.com', '010-4587-1246', '2019-05-01', '0')
SELECT * FROM DUAL;

-- 6. 데이터 수정
UPDATE MEMBER
SET
    REGDATE = SYSDATE
WHERE
    MEMBERID = 'iamuserthree';
    
UPDATE MEMBER
SET
    PHONE = '010-9988-2244',
    USERTYPE = 'USER'
WHERE
    MEMBERID = 'iamusertwo'; 
    
DELETE FROM MEMBER
WHERE
    MEMBERID = 'iamuserone';
    
-- 7. BOARDTABLE에 데이터 삽입
INSERT
INTO BOARD (BOARDNO, TITLE, WRITER, CONTENT)
VALUES (BOARD_SEQUENCE.NEXTVAL, '글쓰기 연습', 'iamusertwo', '글쓰기 연습입니다');

INSERT
INTO BOARD (BOARDNO, TITLE, WRITER, CONTENT, READCOUNT)
VALUES (BOARD_SEQUENCE.NEXTVAL, '글쓰기 연습2', 'iamusertwo', '글쓰기 연습입니다 2', 10);


